### PR TITLE
update for v1.0.0 release

### PR DESCRIPTION
**Pull request by theavey**
re-doing because somehow the repo admin did not have write permissions to my branch (even though allow edits from maintainers was checked)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by theavey** [comment]
@conda-forge-admin, please rerender

**Comment by theavey** [comment]
@conda-forge-admin, please rerender

**Comment by Char-Al** [comment]
Thank you to update this recipe !

Did you have any idea when this version will be available ?

thanks again @theavey !

**Comment by theavey** [comment]
> Thank you to update this recipe !
> 
> Did you have any idea when this version will be available ?
> 
> thanks again @theavey !

No idea. Never done this before, wanted it done, but nothing has happened since I opened this. 

I also do not know why the bot cannot update my branch. I have "allowed edits by maintainers"

**Pull request merged**
