### PR TITLE
update for v1.0.0 release

### PR DESCRIPTION
**Pull request by jsta**
Another attempt at #3, #4. This time forking directly from parent repo.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jsta** [comment]
Checks are passing! Ready for a look @scopatz

**Comment by ocefpaf** [comment]
@jsta this feedstock looks abandoned. Thanks for fixing it! Do you want to add yourself as a maintainer here in this PR?

**Comment by jsta** [comment]
@ocefpaf Done!

**Comment by theavey** [comment]
Excellent, thank you!

**Pull request merged**
